"""
backend/routers/pdf_export.py

OCC Briefing PDF export — generates a one-page operational briefing
for a recovery plan, styled like an actual airline OCC shift handover doc.

Endpoint:
  POST /export/pdf
  Body: { "disruption_event": {...}, "recovery_plan": {...}, "advisory": {...} }
  Returns: PDF file (application/pdf)

Layout:
  Header:   AeroNexus | OCC Recovery Briefing | timestamp
  Section 1: Disruption Summary (type, severity, root flight, affected)
  Section 2: Network Health Score + cascade risk
  Section 3: Recovery Actions (fleet / crew / pax table)
  Section 4: Cost Impact (baseline vs recovery)
  Section 5: Crew Legality Summary
  Section 6: Advisory Text
  Footer:   Generated by AeroNexus v0.3 | FAR 117 checked | Groq LLM
"""

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from datetime import datetime, timezone
import io

router = APIRouter()


def _build_pdf(event: dict, plan: dict, advisory: dict) -> bytes:
    from fpdf import FPDF

    summary = plan.get("summary", {})
    actions = plan.get("final_actions_json", [])

    # action counts
    swaps    = [a for a in actions if a.get("action_type") == "aircraft_swap"    and a.get("feasible")]
    crew_r   = [a for a in actions if a.get("action_type") == "crew_reassign"    and a.get("feasible")]
    rebooks  = [a for a in actions if a.get("action_type") == "passenger_rebook" and a.get("feasible")]
    cancels  = [a for a in actions if a.get("action_type") == "flight_cancel"]
    stranded = [a for a in actions if a.get("action_type") == "passenger_rebook" and not a.get("feasible")]

    # cost estimate
    try:
        from ml.cost_estimator import estimate_cost
        cost_data = estimate_cost(event, plan)
    except Exception:
        cost_data = {}

    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%MZ")

    class PDF(FPDF):
        def header(self):
            self.set_fill_color(10, 25, 60)       # dark navy
            self.rect(0, 0, 210, 18, "F")
            self.set_text_color(255, 255, 255)
            self.set_font("Helvetica", "B", 11)
            self.set_xy(8, 4)
            self.cell(100, 8, "AERONEXUS  |  OCC Recovery Briefing", ln=0)
            self.set_font("Helvetica", "", 8)
            self.set_xy(140, 5)
            self.cell(60, 4, f"Generated: {now_str}", ln=0, align="R")
            self.set_xy(140, 10)
            sev = event.get("severity", "unknown").upper()
            sev_color = {"CRITICAL": (220,50,50), "HIGH": (220,120,0),
                         "MEDIUM": (200,170,0), "LOW": (0,150,80)}.get(sev, (100,100,100))
            self.set_text_color(*sev_color)
            self.set_font("Helvetica", "B", 9)
            self.cell(60, 4, f"SEVERITY: {sev}", ln=0, align="R")
            self.set_text_color(0, 0, 0)
            self.ln(20)

        def footer(self):
            self.set_y(-12)
            self.set_font("Helvetica", "I", 7)
            self.set_text_color(120, 120, 120)
            self.cell(0, 5,
                "AeroNexus v0.3  |  FAR 117 Legality Checked  |  "
                "Cascade Model: XGBoost  |  Advisory: Groq LLaMA-3.3-70b",
                align="C")

        def section_title(self, title: str):
            self.set_fill_color(230, 235, 245)
            self.set_font("Helvetica", "B", 9)
            self.set_text_color(10, 25, 60)
            self.cell(0, 6, f"  {title}", ln=True, fill=True)
            self.ln(1)

        def kv_row(self, label: str, value: str, bold_val: bool = False):
            self.set_font("Helvetica", "", 8)
            self.set_text_color(80, 80, 80)
            self.cell(55, 5, label, ln=0)
            if bold_val:
                self.set_font("Helvetica", "B", 8)
            self.set_text_color(20, 20, 20)
            self.cell(0, 5, str(value), ln=True)

        def table_header(self, cols: list[tuple]):
            self.set_fill_color(10, 25, 60)
            self.set_text_color(255, 255, 255)
            self.set_font("Helvetica", "B", 7)
            for label, w in cols:
                self.cell(w, 5, label, border=0, fill=True)
            self.ln()
            self.set_text_color(0, 0, 0)

        def table_row(self, cols: list[tuple], shade: bool = False):
            if shade:
                self.set_fill_color(245, 247, 252)
            self.set_font("Helvetica", "", 7)
            for val, w in cols:
                self.cell(w, 5, str(val)[:35], border=0, fill=shade)
            self.ln()

    pdf = PDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_left_margin(10)
    pdf.set_right_margin(10)

    # ── Section 1: Disruption Summary ────────────────────────────────────────
    pdf.section_title("1. DISRUPTION SUMMARY")
    pdf.kv_row("Root Flight:",       event.get("root_flight_id", "—"))
    pdf.kv_row("Disruption Type:",   event.get("disruption_type", "—").replace("_", " ").title())
    pdf.kv_row("Severity:",          event.get("severity", "—").upper(), bold_val=True)
    pdf.kv_row("Severity Score:",    str(event.get("severity_score", "—")))
    pdf.kv_row("Affected Flights:",  str(event.get("total_affected_flights", 0)))
    pdf.kv_row("Affected Pax:",      str(event.get("total_affected_pax", 0)))
    pdf.kv_row("Est. Avg Delay:",    f"{event.get('estimated_delay_min', 0)} min")
    pdf.kv_row("Hub Impact:",        str(event.get("hub_airports_affected", [])))
    pdf.ln(3)

    # ── Section 2: Recovery Actions Table ────────────────────────────────────
    pdf.section_title("2. RECOVERY ACTIONS")
    cols = [("Action Type", 45), ("Flight", 25), ("Description", 100), ("Feasible", 20)]
    pdf.table_header(cols)
    display_actions = (swaps + crew_r + rebooks + cancels)[:20]
    for i, a in enumerate(display_actions):
        pdf.table_row([
            (a.get("action_type","").replace("_"," ").title(), 45),
            (a.get("flight_number","—"), 25),
            (a.get("description","")[:80], 100),
            ("✓" if a.get("feasible") else "✗", 20),
        ], shade=(i % 2 == 0))
    if len(actions) > 20:
        pdf.set_font("Helvetica", "I", 7)
        pdf.set_text_color(100,100,100)
        pdf.cell(0, 4, f"  ... and {len(actions)-20} more actions", ln=True)
        pdf.set_text_color(0,0,0)
    pdf.ln(3)

    # ── Section 3: Plan Metrics ───────────────────────────────────────────────
    pdf.section_title("3. PLAN METRICS")
    left_items = [
        ("Aircraft Swaps:",         len(swaps)),
        ("Crew Reassignments:",     len(crew_r)),
        ("Passengers Rebooked:",    len(rebooks)),
        ("Flights Cancelled:",      len(cancels)),
        ("Stranded Pax (manual):",  len(stranded)),
    ]
    right_items = [
        ("Cancellations Avoided:",  summary.get("cancellations_avoided", 0)),
        ("Misconnects Avoided:",    summary.get("misconnects_avoided", 0)),
        ("Delay Reduction:",        f"{summary.get('total_delay_reduction_min',0)} min"),
        ("Conflicts Detected:",     summary.get("conflict_count", 0)),
        ("FAR 117 Checked:",        "Yes"),
    ]
    y_start = pdf.get_y()
    for label, val in left_items:
        pdf.kv_row(label, str(val))
    y_end = pdf.get_y()

    # right column
    pdf.set_xy(110, y_start)
    for label, val in right_items:
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(80, 80, 80)
        pdf.set_x(110)
        pdf.cell(55, 5, label, ln=0)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(20, 20, 20)
        pdf.cell(0, 5, str(val), ln=True)
    pdf.set_y(max(y_end, pdf.get_y()))
    pdf.ln(3)

    # ── Section 4: Cost Impact ────────────────────────────────────────────────
    pdf.section_title("4. COST IMPACT")
    if cost_data:
        baseline = cost_data.get("baseline_cost_usd", 0)
        recovery = cost_data.get("recovery_cost_usd", 0)
        saving   = cost_data.get("net_saving_usd", 0)
        pdf.kv_row("Baseline Cost (no action):", f"${baseline:,.0f}")
        pdf.kv_row("Recovery Plan Cost:",        f"${recovery:,.0f}")

        pdf.set_font("Helvetica", "B", 9)
        color = (0,140,70) if saving > 0 else (200,50,50)
        pdf.set_text_color(*color)
        pdf.cell(55, 6, "Net Saving:", ln=0)
        pdf.cell(0, 6, f"${saving:,.0f}", ln=True)
        pdf.set_text_color(0,0,0)
    else:
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(120,120,120)
        pdf.cell(0, 5, "Cost estimator not available — install ml/cost_estimator.py", ln=True)
        pdf.set_text_color(0,0,0)
    pdf.ln(3)

    # ── Section 5: Crew Legality Summary ─────────────────────────────────────
    pdf.section_title("5. CREW LEGALITY (FAR 117)")
    crew_actions = [a for a in actions if a.get("action_type") == "crew_reassign"]
    far_on = any(
        a.get("metadata", {}).get("far117_checked") for a in crew_actions
    )
    pdf.kv_row("FAR 117 Enforcement:", "Enabled" if far_on else "Fallback mode")

    violations = 0
    warnings   = 0
    for a in crew_actions:
        for assign in a.get("metadata", {}).get("assignments", []):
            leg = assign.get("legality", {})
            violations += 0   # legal crew only assigned; count rejected
        for rej in a.get("metadata", {}).get("rejected_crew", []):
            violations += len(rej.get("violations", []))
            warnings   += len(rej.get("warnings", []))

    pdf.kv_row("Crew Violations Found:", str(violations))
    pdf.kv_row("Crew Warnings:",         str(warnings))

    if crew_actions:
        sample = crew_actions[0].get("metadata", {}).get("assignments", [])[:3]
        for a in sample:
            leg = a.get("legality", {})
            if leg:
                used = leg.get("used_fdp_min", 0)
                mx   = leg.get("max_fdp_min", 0)
                pct  = round(used / mx * 100) if mx else 0
                pdf.set_font("Helvetica", "", 7)
                pdf.set_text_color(60,60,60)
                pdf.cell(0, 4,
                    f"  {a.get('name','?')} ({a.get('role','?')}): "
                    f"FDP {used:.0f}/{mx}min ({pct}%)"
                    + (" ⚠ " + "; ".join(leg.get("warnings",[])) if leg.get("warnings") else ""),
                    ln=True)
        pdf.set_text_color(0,0,0)
    pdf.ln(3)

    # ── Section 6: OCC Advisory ───────────────────────────────────────────────
    pdf.section_title("6. OCC ADVISORY")
    adv_text = advisory.get("summary", "No advisory generated.")
    bullets  = advisory.get("bullets", [])
    llm_used = advisory.get("llm_used", False)

    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(30,30,30)
    pdf.multi_cell(0, 5, adv_text)
    pdf.ln(2)

    for b in bullets[:8]:
        pdf.set_font("Helvetica", "", 8)
        clean = b.lstrip("•-* ").strip()
        if clean:
            pdf.cell(5, 4, "•", ln=0)
            pdf.multi_cell(0, 4, clean)

    pdf.ln(2)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(120,120,120)
    source = "Groq LLaMA-3.3-70b" if llm_used else "Rule-based fallback"
    pdf.cell(0, 4, f"Advisory source: {source}", ln=True)

    return bytes(pdf.output())


@router.post("/pdf")
def export_pdf(body: dict):
    """
    Body: {
      "disruption_event": {...},
      "recovery_plan":    {...},
      "advisory":         {...}   (optional)
    }
    Returns: PDF binary (application/pdf).
    """
    event    = body.get("disruption_event")
    plan     = body.get("recovery_plan")
    advisory = body.get("advisory", {})

    if not event or not plan:
        raise HTTPException(400, detail="disruption_event and recovery_plan required")

    try:
        pdf_bytes = _build_pdf(event, plan, advisory)
    except Exception as e:
        raise HTTPException(500, detail=f"PDF generation failed: {e}")

    flight_id = event.get("root_flight_id", "unknown")
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M")
    filename  = f"aeronexus_briefing_{flight_id}_{timestamp}.pdf"

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )